# Generated by Django 6.0.3 on 2026-03-31 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254)),
                ('autor', models.CharField(max_length=254)),
                ('ano_publicado', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateTimeField()),
                ('data_devolvido', models.DateTimeField(blank=True, null=True)),
                ('multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.usuario')),
            ],
        ),
    ]
